FROM aquariuslt/weblogic:12.2.1.2-developer

MAINTAINER Aquariuslt <superaquariuslt@gmail.com>

# Install zip unzip to download and un-archive package config
USER root
RUN yum install zip unzip -y

USER oracle
